apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-app

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: flask-backend
    newName: production-registry/flask-backend
    newTag: v1.0.0

secretGenerator:
  - name: flask-secrets
    type: kubernetes.io/tls
    files:
      - tls.crt=./tls.crt
      - tls.key=./tls.key
    options:
      disableNameSuffixHash: true