apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-sa
  namespace: flask-app
  labels:
    app: flask-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-role
  namespace: flask-app
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-rolebinding
  namespace: flask-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flask-role
subjects:
- kind: ServiceAccount
  name: flask-sa
  namespace: flask-app